---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: financeme
  labels:
    app: financeme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: financeme
  template:
    metadata:
      labels:
        app: financeme
    spec:
      containers:
        - name: financeme
          image: rahul9041/financeme:latest
          ports:
            - containerPort: 8081
          env:
            - name: PORT
              value: "8081"
          readinessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: financeme
  labels:
    app: financeme
spec:
  type: NodePort
  selector:
    app: financeme
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 31282
