---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: financeme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: financeme
  template:
    metadata:
      labels:
        app: financeme
    spec:
      containers:
        - name: financeme
          image: rahul9041/financeme:latest
          ports:
            - containerPort: 8081
          env:
            - name: PORT
              value: "8081"
---
apiVersion: v1
kind: Service
metadata:
  name: financeme
spec:
  type: NodePort
  selector:
    app: financeme
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 31282
